### ISSUE TITLE
ImportError: cannot import name getcwd

### ISSUE THREAD

**Issue by bitsgalore** [titusz/epubcheck#1]
I just tried to get the wrapper running under Linux Mint. Installation using pip appears to be successful, but then when I run the wrapper using the CLI:

```
epubcheck
```

I end up with this:

```
Traceback (most recent call last):
  File "/usr/local/bin/epubcheck", line 7, in <module>
    from epubcheck.cli import main
  File "/usr/local/lib/python2.7/dist-packages/epubcheck/cli.py", line 8, in <module>
    from six.moves import getcwd
ImportError: cannot import name getcwd
```

Which is strange because Six is already installed on my system (version: 1.5.2). I'm using Python 2.7.6.

This problem does not occur if I build/install the wrapper from its source using _setup.py_ (`sudo python setup.py install`), so I think this is some sort of packaging issue?

**Comment by titusz** [comment]
Thats strange. I made some changes, removed the dependancy on six and made a new release at PyPi: https://pypi.python.org/pypi/epubcheck/0.3.1

Let me know if that fixes the issue for you.

**Comment by bitsgalore** [comment]
Sorry for the somewhat late response, but I just tried the changed version, and I can confirm that it now works for me. Thanks!

**Comment by titusz** [comment]
You´re welcome :)
