### ISSUE TITLE
Switch -x results in AttributeError

### ISSUE THREAD

**Issue by bitsgalore** [titusz/epubcheck#10]
I just tried to generate XLS output for a directory with some EPUBs. I used the following command:

```
epubcheck -x test.xls ./samples-test/
```

But this results in an AttributeError (output file is created, but it is empty):

```
AttributeError: 'Databook' object has no attribute 'xls'
```

Environment:

- Python 3.8.10
- Linux Mint 20.1 Ulyssa

**Comment by titusz** [comment]
Thanks for reporting the bug. I just released a new version that should fix this error. Can you confirm that it works now?

**Comment by bitsgalore** [comment]
Works fine now, thanks for fixing this!
